// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vhpcinfpnnsmbqkvlvrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZocGNpbmZwbm5zbWJxa3ZsdnJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDIyMDMsImV4cCI6MjA2NDg3ODIwM30.jnOGYshZWOhKuymImZ5rfvIB_9JPRJPS34t-N4bNVgU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);